server:
  port: 7878

spring:
    datasource:
        url: jdbc:mysql://localhost:3307/shiro?useSSL=false
        username: root
        password: 123456
        # 使用druid数据源
        driver-class-name: com.mysql.jdbc.Driver
        tomcat:
          max-idle: 10
          max-wait: 10000
          min-idle: 5
          initial-size: 5
    redis:
      database: 0
      host: localhost
      password: foobared
      port: 6379
      timeout: 3000
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0


mybatis:
  type-aliases-package: com.example.shiroweb.entity
  mapper-locations: classpath:mapper/*.xml  # 注意：对应实体类的路径

logging:
  level:
    com:
      example:
        shiroweb:
          mapper: debug

